---
title: "Analysis of Australian Population from 2011 to 2016"
author: "Yuhan Wang"
date: 2021-11-18T21:13:14-05:00
categories: ["R"]
tags: ["Population", "Australia", "Age structure"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
library(rmarkdown)
library(blogdown)
```

Population structure and aging is one of the problems that countries around the world have to solve in order to develop and balance due to factors such as health care and migration. Besides, the growth rate of the total population also decreased, with the growth rate in 2015 dropping by 2% compared with 2011, while the increase of residents under 20 years old also decreased.  

Here I analyse the demographic structure and aging trend from 2011 to 2016:

<iframe src="https://public.tableau.com/views/Populationanalysis1/1?:showVizHome=no&:embed=true"width="800"height="830"></iframe>

## Age distribution by Sex

The sex ratio is important because the imbalance between men and women can lead to problems and even social instability.In Australia. In Australia, for every thousand men there are twelve hundred women, which means the gender distribution is a little uneven. In addition, it is noteworthy that the population of women over eighty-five is much higher than that of men.  

<iframe src="https://public.tableau.com/views/Populationanalysis_16371665109340/Sexratio?:showVizHome=no&:embed=true"width="400"height="200"></iframe>

Here is the distribution of the population by age and gender:

<iframe src="https://public.tableau.com/views/Populationanalysis2/4?:showVizHome=no&:embed=true"width="800"height="830"></iframe>


## Median age in different state in 2016

The median represents a state's Labour force and productivity, and the higher the median, the younger the population tends to be, partly reflecting the state's lower state pension contributions and lower health-care burden.  

<iframe src="https://public.tableau.com/views/Populationanalysis1/Medianageofdifferentstate?:showVizHome=no&:embed=true"width="800"height="830"></iframe>

### Districts with a Population Density of over 10,000/KM^2

The denser the population, the more attractive the area, and the higher the house price. Melbourne even has a population density of 17,000.

<iframe src="https://public.tableau.com/views/Populationanalysis1/AreathatPopulationDensityover10000km2?:showVizHome=no&:embed=true"width="800"height="400"></iframe>

## Changes in the overseas born population

The table reflects the change in the number of people born overseas in 2016 compared with 2011. Immigration from Asia increased by more than 70 percent, while that from Europe as a whole fell by about 20 percent  

<iframe src="https://public.tableau.com/views/Populationanalysis1/2_1?:showVizHome=no&:embed=true"width="800"height="750"></iframe>


In conclusion, this visualization reflects the age and gender distribution and changes of the Australian population from 2011 to 2016, and the analysis can help government departments adjust national policies accordingly.  For example, the European immigration policy should be relaxed to attract talents and maintain cultural diversity. Secondly, timely intervention should be made for the aging population to reduce its negative impact on Australia.  

Dataset from Population and People, ASGS, 2011-2016